name: mamba_weather
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python
  - pytorch
  - numpy
  - einops
  - tqdm
  - xarray
  - zarr
  - dask
  - gcsfs
  - pip:
    - triton


